
'use strict';
const CONFIG={lessonId:'UCAN-L16',packageVersion:'v1.3_Final_Learner_Experience',storageKey:'ucan.lesson16.v1',schemaVersion:2,currentLessonLabel:'Заняття 16',previousUrl:'https://clusterceu-crypto.github.io/UCAN-Lesson15/',nextUrl:'https://clusterceu-crypto.github.io/UCAN-Lesson17/',routes:[
{label:'Навіщо Вам це заняття',slug:'navishcho'},{label:'Відходи як ресурс',slug:'vidkhody-yak-resurs'},{label:'Стратегія — система виборів',slug:'stratehiia-systema'},{label:'Стратегічні орієнтири',slug:'stratehichni-oriientyry'},{label:'Різні умови — різні рішення',slug:'rizni-umovy'},{label:'Формативна практика',slug:'formatyvna-praktyka'},{label:'Перед практичною роботою',slug:'pered-praktychnoiu-robotoiu'},{label:'Практичне завдання',slug:'praktychne-zavdannia'},{label:'Для подальшого опрацювання',slug:'dlia-podalshoho-opratsiuuvannia'},{label:'Підсумкове оцінювання',slug:'pidsumkove-otsiniuvannia'},{label:'Завершення',slug:'zavershennia'}]};
const FINAL_CORRECT=[1,3,0,2,1];
const DEFAULT_STATE=()=>({schemaVersion:2,routeOrderVersion:2,route:0,artifact:{savedText:''},formative:{selected:null,checked:false,correct:false},selfCheck:[false,false,false,false],assessment:{answers:[null,null,null,null,null],checkedAnswers:null,checkedScore:null,dirty:false,passed:false},completion:{passed:false}});
let state=DEFAULT_STATE(); let artifactDraft=''; let storageAvailable=true; let qaPreview=false; let qaReturnRoute=0; let dialogAction=null; let dialogInvoker=null; let visualDialogInvoker=null;
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function safeLoad(){try{const raw=localStorage.getItem(CONFIG.storageKey);if(!raw)return;const parsed=JSON.parse(raw);if(parsed&&parsed.schemaVersion===2){const legacyRouteOrder=parsed.routeOrderVersion!==2;state={...DEFAULT_STATE(),...parsed,artifact:{...DEFAULT_STATE().artifact,...(parsed.artifact||{})},formative:{...DEFAULT_STATE().formative,...(parsed.formative||{})},assessment:{...DEFAULT_STATE().assessment,...(parsed.assessment||{})},completion:{...DEFAULT_STATE().completion,...(parsed.completion||{})}};if(legacyRouteOrder){if(state.route===8)state.route=9;else if(state.route===9)state.route=8;state.routeOrderVersion=2}}else if(parsed&&parsed.schemaVersion===1){const savedText=typeof parsed.artifact?.savedText==='string'?parsed.artifact.savedText:'';state=DEFAULT_STATE();state.artifact.savedText=savedText}else{state=DEFAULT_STATE()}if(!Array.isArray(state.selfCheck)||state.selfCheck.length!==4)state.selfCheck=[false,false,false,false];if(!Array.isArray(state.assessment.answers)||state.assessment.answers.length!==5)state.assessment.answers=[null,null,null,null,null]}catch(e){storageAvailable=false;state=DEFAULT_STATE()}}
function safeSave(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(state));storageAvailable=true;return true}catch(e){storageAvailable=false;return false}}
function announce(msg){const el=$('#globalStatus');el.textContent=msg;el.classList.remove('visually-hidden');setTimeout(()=>el.classList.add('visually-hidden'),4500)}
function completionUnlocked(){return !!(state.assessment.passed&&!state.assessment.dirty&&state.completion.passed)}
function routeAllowed(i){if(i===10)return completionUnlocked()||qaPreview;return true}
function currentVisibleRoute(){return qaPreview?10:state.route}
function focusRouteStart(){const main=$('#lessonMain');if(main)main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'})}
function setRoute(i,{push=true,focus=true}={}){if(qaPreview)return;if(i<0||i>10)return;if(!routeAllowed(i)){announce('Завершення відкриється після успішного підсумкового оцінювання.');return}state.route=i;safeSave();renderRoute({focus:false});if(push)history.pushState({route:i},'',`#${CONFIG.routes[i].slug}`);if(focus)focusRouteStart()}
function renderRoute({focus=false}={}){const i=currentVisibleRoute();$$('.route').forEach((el,idx)=>el.hidden=idx!==i);$('#currentSection').textContent=CONFIG.routes[i].label;const percent=(i===10?100:Math.round(((i+1)/11)*100));$('#pagePosition').textContent=`Сторінка ${i+1} з 11`;$('#navPosition').textContent=`Сторінка ${i+1} з 11`;$('#percentText').textContent=`${percent}%`;$('#progressBar').value=percent;$('#progressBar').textContent=`${percent}%`;const nextLessonLink=$('#nextLessonLink');if(nextLessonLink){nextLessonLink.href=CONFIG.nextUrl||'#';nextLessonLink.hidden=!CONFIG.nextUrl}const back=$('#navBack'),next=$('#navNext');back.disabled=qaPreview||i===0;next.hidden=i===10;next.disabled=qaPreview||(i===9&&!completionUnlocked());$('#resetButton').disabled=qaPreview;next.innerHTML='Далі <span aria-hidden="true">→</span>';updateRouteMap();syncControls();if(focus){$('#lessonMain').focus({preventScroll:true})}}
function updateRouteMap(){const i=currentVisibleRoute();const nav=$('#routeMap');if(!nav.childElementCount){CONFIG.routes.forEach((r,idx)=>{const b=document.createElement('button');b.type='button';b.textContent=r.label;b.dataset.route=String(idx);b.addEventListener('click',()=>setRoute(idx));nav.appendChild(b)})}Array.from(nav.children).forEach((b,idx)=>{b.setAttribute('aria-current',idx===i?'page':'false');b.disabled=qaPreview||(idx===10&&!completionUnlocked())})}
function syncControls(){const ta=$('#artifactText');if(ta&&document.activeElement!==ta)ta.value=artifactDraft;$$('[data-selfcheck]').forEach((el,idx)=>{el.checked=!!state.selfCheck[idx]});const fSel=state.formative.selected;$$('input[name="formative"]').forEach(el=>{el.checked=el.value===fSel});const fStatus=$('#formativeStatus'),fFb=$('#formativeFeedback');if(fStatus&&state.formative.checked){fStatus.textContent=state.formative.correct?'Правильно.':'Потребує перегляду.';fStatus.className='feedback '+(state.formative.correct?'status-correct':'status-review');fFb.hidden=false}else if(fStatus){fStatus.textContent='';fStatus.className='feedback';if(fFb)fFb.hidden=true}
state.assessment.answers.forEach((ans,idx)=>{$$(`input[name="q${idx+1}"]`).forEach(el=>{el.checked=ans!==null&&Number(el.value)===ans})});renderAssessmentResults()}
function renderAssessmentResults(){for(let i=0;i<5;i++){const status=$(`#q${i+1}Status`),fb=$(`#q${i+1}Feedback`);if(!status||!fb)continue;if(state.assessment.checkedScore===null||state.assessment.dirty){status.textContent='';status.className='item-status';fb.hidden=true;continue}const correct=state.assessment.checkedAnswers&&state.assessment.checkedAnswers[i]===FINAL_CORRECT[i];status.textContent=correct?'Правильно.':'Потребує перегляду.';status.className='item-status '+(correct?'status-correct':'status-review');fb.hidden=false}const overall=$('#finalStatus');if(overall){if(state.assessment.dirty){overall.textContent='Відповіді змінено. Перевірте їх ще раз.';overall.className='feedback status-review'}else if(state.assessment.checkedScore!==null){overall.textContent=state.assessment.passed?'Усі 5 відповідей правильні. Завершення відкрито.':`Правильних відповідей: ${state.assessment.checkedScore} з 5. Спробуйте ще раз.`;overall.className='feedback '+(state.assessment.passed?'status-correct':'status-review')}else{overall.textContent='';overall.className='feedback'}}}
function openDialog(title,text,confirmLabel,action,invoker){dialogAction=action;dialogInvoker=invoker;$('#dialogTitle').textContent=title;$('#dialogText').textContent=text;$('#dialogConfirm').textContent=confirmLabel;const d=$('#confirmDialog');d.showModal();$('#dialogCancel').focus()}
function closeDialogReturnFocus(){const inv=dialogInvoker;dialogInvoker=null;setTimeout(()=>inv?.focus(),0)}
function resetLesson(){const saved=state.artifact.savedText;const currentDraft=artifactDraft;state=DEFAULT_STATE();state.artifact.savedText=saved;artifactDraft=currentDraft;safeSave();qaPreview=false;history.replaceState({route:0},'',`#${CONFIG.routes[0].slug}`);renderRoute();announce('Прогрес заняття скинуто. Ваша рамка збережена.');$('#resetButton').focus()}
function deleteArtifact(){state.artifact.savedText='';artifactDraft='';safeSave();const ta=$('#artifactText');if(ta)ta.value='';$('#artifactStatus').textContent='Рамку видалено.';announce('Рамку видалено.');}
function initEvents(){
$$('.visual-zoom').forEach(btn=>btn.addEventListener('click',()=>{visualDialogInvoker=btn;const img=$('#visualDialogImage');img.src=btn.dataset.visualSrc;img.alt=btn.dataset.visualAlt||'';const d=$('#visualDialog');d.showModal();$('#visualDialogClose').focus()}));
$('#visualDialogClose').addEventListener('click',()=>$('#visualDialog').close());
$('#visualDialog').addEventListener('close',()=>{const inv=visualDialogInvoker;visualDialogInvoker=null;if(inv)setTimeout(()=>inv.focus(),0)});
$('#navBack').addEventListener('click',()=>setRoute(currentVisibleRoute()-1));$('#navNext').addEventListener('click',()=>setRoute(currentVisibleRoute()+1));
$('#resetButton').addEventListener('click',e=>openDialog('Почати заняття спочатку?','Буде очищено прогрес, формативну практику, самоперевірку, підсумкове оцінювання та стан завершення. Ваша збережена рамка залишиться.','Почати спочатку','reset',e.currentTarget));
$('#confirmDialog').addEventListener('close',()=>{const v=$('#confirmDialog').returnValue;if(v==='confirm'&&dialogAction==='reset')resetLesson();else if(v==='confirm'&&dialogAction==='deleteArtifact')deleteArtifact();closeDialogReturnFocus();dialogAction=null});
$('#artifactText').addEventListener('input',e=>{artifactDraft=e.target.value});$('#saveArtifact').addEventListener('click',()=>{state.artifact.savedText=artifactDraft;const ok=safeSave();const st=$('#artifactStatus');st.textContent=ok?'Рамку збережено локально на цьому пристрої.':'Локальне збереження недоступне. Текст залишається у відкритій сторінці до її закриття.';st.className='feedback '+(ok?'status-correct':'status-review')});
$('#deleteArtifact').addEventListener('click',e=>openDialog('Видалити рамку?','Буде видалено лише Ваш текст практичного артефакту. Результати підсумкового оцінювання та завершення не зміняться.','Видалити рамку','deleteArtifact',e.currentTarget));
$('#downloadPdf').addEventListener('click',downloadArtifactPdf);
$$('[data-selfcheck]').forEach((el,idx)=>el.addEventListener('change',()=>{state.selfCheck[idx]=el.checked;safeSave()}));
$$('input[name="formative"]').forEach(el=>el.addEventListener('change',()=>{state.formative.selected=el.value;state.formative.checked=false;state.formative.correct=false;safeSave();syncControls()}));
$('#checkFormative').addEventListener('click',()=>{if(!state.formative.selected){$('#formativeStatus').textContent='Оберіть один варіант відповіді.';$('#formativeStatus').className='feedback status-review';return}state.formative.checked=true;state.formative.correct=state.formative.selected==='B';safeSave();syncControls()});
for(let i=0;i<5;i++)$$(`input[name="q${i+1}"]`).forEach(el=>el.addEventListener('change',()=>{state.assessment.answers[i]=Number(el.value);if(state.assessment.checkedScore!==null){state.assessment.dirty=true;state.assessment.passed=false;state.completion.passed=false}safeSave();renderAssessmentResults();updateRouteMap();renderRoute()}));
$('#checkFinal').addEventListener('click',()=>{if(state.assessment.answers.some(v=>v===null)){const st=$('#finalStatus');st.textContent='Відповідайте на всі 5 запитань перед перевіркою.';st.className='feedback status-review';return}const answers=[...state.assessment.answers];let score=0;answers.forEach((v,i)=>{if(v===FINAL_CORRECT[i])score++});state.assessment.checkedAnswers=answers;state.assessment.checkedScore=score;state.assessment.dirty=false;state.assessment.passed=score===5;state.completion.passed=score===5;safeSave();renderAssessmentResults();updateRouteMap();renderRoute()});
window.addEventListener('popstate',e=>{if(qaPreview)return;let target=Number.isInteger(e.state?.route)?e.state.route:CONFIG.routes.findIndex(r=>location.hash===`#${r.slug}`);if(target<0)target=state.route;if(target===10&&!completionUnlocked())target=9;state.route=target;safeSave();renderRoute({focus:false});focusRouteStart()});
const qa=new URLSearchParams(location.search).get('qa')==='1';if(qa){$('#qaPanel').hidden=false;$('#qaPreviewCompletion').addEventListener('click',()=>{qaReturnRoute=state.route;qaPreview=true;renderRoute();$('#qaPreviewCompletion').hidden=true;$('#qaExitPreview').hidden=false});$('#qaExitPreview').addEventListener('click',()=>{qaPreview=false;state.route=qaReturnRoute;renderRoute();$('#qaPreviewCompletion').hidden=false;$('#qaExitPreview').hidden=true})}
}
function wrapCanvasText(ctx,text,maxWidth){const paras=text.replace(/\r/g,'').split('\n');const lines=[];for(const para of paras){if(!para.trim()){lines.push('');continue}const words=para.split(/\s+/);let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line)}return lines}
function canvasPage(){const c=document.createElement('canvas');c.width=1240;c.height=1754;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#17212b';return {c,ctx}}
function jpegBytes(canvas){const b64=canvas.toDataURL('image/jpeg',.94).split(',')[1];const bin=atob(b64);const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function asciiBytes(s){return new TextEncoder().encode(s)}
function concatBytes(arrs){const n=arrs.reduce((a,b)=>a+b.length,0);const out=new Uint8Array(n);let p=0;for(const a of arrs){out.set(a,p);p+=a.length}return out}
function buildImagePdf(images,wpx=1240,hpx=1754){const objs=[];const pageIds=[],imgIds=[],contentIds=[];let next=3;for(let i=0;i<images.length;i++){pageIds.push(next++);imgIds.push(next++);contentIds.push(next++)}objs[1]=asciiBytes('<< /Type /Catalog /Pages 2 0 R >>');objs[2]=asciiBytes(`<< /Type /Pages /Count ${images.length} /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] >>`);for(let i=0;i<images.length;i++){const pid=pageIds[i],iid=imgIds[i],cid=contentIds[i],name=`Im${i+1}`;objs[pid]=asciiBytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /${name} ${iid} 0 R >> >> /Contents ${cid} 0 R >>`);const imHead=asciiBytes(`<< /Type /XObject /Subtype /Image /Width ${wpx} /Height ${hpx} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${images[i].length} >>\nstream\n`);const imTail=asciiBytes('\nendstream');objs[iid]=concatBytes([imHead,images[i],imTail]);const stream=`q\n595.28 0 0 841.89 0 0 cm\n/${name} Do\nQ\n`;objs[cid]=asciiBytes(`<< /Length ${stream.length} >>\nstream\n${stream}endstream`)}let chunks=[asciiBytes('%PDF-1.3\n%UCAN\n')],offsets=[0],pos=chunks[0].length;for(let id=1;id<objs.length;id++){offsets[id]=pos;const pre=asciiBytes(`${id} 0 obj\n`),post=asciiBytes('\nendobj\n');chunks.push(pre,objs[id],post);pos+=pre.length+objs[id].length+post.length}const xrefPos=pos;let xref=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let id=1;id<objs.length;id++)xref+=String(offsets[id]).padStart(10,'0')+' 00000 n \n';xref+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;chunks.push(asciiBytes(xref));return new Blob(chunks,{type:'application/pdf'})}
function createArtifactPdf(text){const pages=[];let {c,ctx}=canvasPage(),y=110;const max=1040,bottom=1640;ctx.font='700 38px Arial, sans-serif';ctx.fillStyle='#17324d';ctx.fillText('Портфель мера',100,y);y+=62;ctx.font='700 27px Arial, sans-serif';const title='Управлінська рамка стратегії управління ТПВ “відходи як ресурс”';for(const line of wrapCanvasText(ctx,title,max)){ctx.fillText(line,100,y);y+=38}y+=28;ctx.fillStyle='#17212b';ctx.font='22px Arial, sans-serif';const lines=wrapCanvasText(ctx,text||'',max);function newPage(){pages.push(jpegBytes(c));({c,ctx}=canvasPage());ctx.fillStyle='#17212b';ctx.font='22px Arial, sans-serif';y=105}for(const line of lines){if(y+32>bottom)newPage();ctx.fillText(line,100,y);y+=32}pages.push(jpegBytes(c));return buildImagePdf(pages)}
function downloadArtifactPdf(){const st=$('#artifactStatus');try{const blob=createArtifactPdf(artifactDraft);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Портфель_мера_Стратегія_ТПВ.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);st.textContent='PDF підготовлено локально.';st.className='feedback status-correct'}catch(e){st.textContent='Не вдалося підготувати PDF на цьому пристрої.';st.className='feedback status-review'}}
function init(){safeLoad();artifactDraft=state.artifact.savedText||'';initEvents();const hashIndex=CONFIG.routes.findIndex(r=>location.hash===`#${r.slug}`);if(hashIndex>=0&&routeAllowed(hashIndex))state.route=hashIndex;if(state.route===10&&!completionUnlocked())state.route=9;history.replaceState({route:state.route},'',`${location.pathname}${location.search}#${CONFIG.routes[state.route].slug}`);safeSave();renderRoute()}
document.addEventListener('DOMContentLoaded',init);
